// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Chartist = require("chartist");

new Chartist.Line(".ct-chart", {
      labels: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ],
      series: [[
          12,
          9,
          7,
          8,
          5
        ]]
    }, {
      lineSmooth: false
    });

new Chartist.Bar(".ct-bar-chart", {
      labels: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ],
      series: [
        [
          12,
          9,
          7,
          8,
          5
        ],
        [
          2,
          29,
          4,
          8.4,
          34
        ]
      ]
    }, undefined);

new Chartist.Bar(".ct-hbar-chart", {
      labels: [
        "Mon",
        "Tue",
        "Wed",
        "Thr",
        "Fri"
      ],
      series: [
        [
          12,
          9,
          7,
          8,
          5
        ],
        [
          2,
          29,
          4,
          8.4,
          34
        ]
      ]
    }, {
      chartPadding: {
        top: 10,
        right: 10,
        bottom: 10,
        left: 10
      },
      fullWidth: false,
      reverseData: true,
      seriesBarDistance: 10,
      horizontalBars: true
    });

new Chartist.Line(".ct-area-chart", {
      labels: [
        "Monday",
        "Tuesday",
        "Wednesday",
        "Thursday",
        "Friday"
      ],
      series: [[
          2,
          29,
          4,
          8.4,
          34
        ]]
    }, {
      low: 0.0,
      showArea: true
    });

new Chartist.Line(".ct-biarea-chart", {
      labels: [
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8"
      ],
      series: [
        [
          1,
          2,
          3,
          1,
          -2,
          0,
          1,
          0
        ],
        [
          -2,
          -1,
          -2,
          -1,
          -2.5,
          -1,
          -2,
          -1
        ],
        [
          0,
          0,
          0,
          1,
          2,
          2.5,
          2,
          1
        ],
        [
          2.5,
          2,
          1,
          0.5,
          1,
          0.5,
          -1,
          -2.5
        ]
      ]
    }, {
      low: -3.0,
      high: 3.0,
      showArea: true,
      showLine: false,
      showPoint: false,
      fullWidth: true,
      axisX: {
        showLabel: true,
        showGrid: true
      }
    });

new Chartist.Line(".ct-timeseries-chart", {
      series: [{
          data: [
            {
              x: new Date("2021-07-16T00:00:00Z00:00"),
              y: 53
            },
            {
              x: new Date("2021-07-17T00:00:00Z00:00"),
              y: 40
            },
            {
              x: new Date("2021-07-18T00:00:00Z00:00"),
              y: 45
            },
            {
              x: new Date("2021-07-19T00:00:00Z00:00"),
              y: 40
            },
            {
              x: new Date("2021-07-20T00:00:00Z00:00"),
              y: 20
            },
            {
              x: new Date("2021-07-21T00:00:00Z00:00"),
              y: 32
            },
            {
              x: new Date("2021-07-22T00:00:00Z00:00"),
              y: 18
            },
            {
              x: new Date("2021-07-23T00:00:00Z00:00"),
              y: 11
            }
          ]
        }]
    }, {
      showPoint: false,
      fullWidth: true,
      axisX: {
        showLabel: true,
        showGrid: true
      }
    });

new Chartist.Pie(".ct-pie-chart", {
      labels: [
        "Bananas",
        "Apples",
        "Grapes"
      ],
      series: [
        20,
        40,
        40
      ]
    }, {
      total: 100,
      labelInterpolationFnc: (function (x) {
          return x;
        })
    });

new Chartist.Pie(".ct-donut-chart", {
      labels: [
        "Bananas",
        "Apples",
        "Grapes"
      ],
      series: [
        20,
        40,
        40
      ]
    }, {
      donut: true,
      donutWidth: 20,
      total: 100,
      labelInterpolationFnc: (function (x) {
          return x;
        })
    });

new Chartist.Line(".ct-scatter-chart", {
      series: [[
          {
            x: 0.13,
            y: 0.54
          },
          {
            x: 0.47,
            y: 0.84
          },
          {
            x: 0.53,
            y: 0.58
          },
          {
            x: 0.63,
            y: 0.94
          },
          {
            x: 0.23,
            y: 0.24
          },
          {
            x: 0.23,
            y: 0.14
          },
          {
            x: 0.23,
            y: 0.4
          },
          {
            x: 0.03,
            y: 0.24
          },
          {
            x: 0.83,
            y: 0.24
          },
          {
            x: 0.03,
            y: 0.84
          },
          {
            x: 0.03,
            y: 0.24
          },
          {
            x: 0.33,
            y: 0.54
          },
          {
            x: 0.73,
            y: 0.54
          }
        ]]
    }, {
      low: 0.0,
      high: 1.0,
      showLine: false,
      showPoint: true,
      axisX: {
        showLabel: true,
        type: Chartist.AutoScaleAxis
      }
    });

/*  Not a pure module */
